#!/bin/sh
### BEGIN INIT INFO
# Provides:             logtoram
# Required-Start:       $remote_fs $time logtoram
# Required-Stop:        umountnfs $time logtoram
# X-Start-Before:       $syslog
# X-Stop-After:         $syslog
# Default-Start:        2 3 5
# Default-Stop:         0 1 6
# Short-Description:    /var/log
# Description:          FS 2 RAM (boot)
#                       RAM 2 FS (sync)
#                       RAM 2 FS (shutdown / reboot)
### END INIT INFO


#pi3 req:
set -o errexit -o nounset -o xtrace

RSYNC="/usr/bin/rsync"
RSYNCCONF_TO_RAM="--recursive --links --checksum --perms --partial --times --group --owner --devices --specials --exclude='*.gz' --exclude='*.1'"
RSYNCCONF_TO_BAK="--recursive --links --checksum --perms --partial --times --group --owner --devices --specials --exclude='*.gz' --exclude='*.1'"

DIR_LOG="/var/log/"
DIR_BAK="/var/log_bak/"

BAK_to_RAM="$RSYNC $RSYNCCONF_TO_RAM $DIR_BAK $DIR_LOG"
LOG_to_BAK="$RSYNC $RSYNCCONF_TO_BAK $DIR_LOG $DIR_BAK"

case $1 in
    start)
        echo "start, sync log backup to ramfs.."
        $BAK_to_RAM
        echo "done."
        ;;
    sync)
        echo "sync ramfs to log backup.."
        $LOG_to_BAK
        echo "done."
        ;;
    stop)
        echo "stop, sync ramfs to log backup.."
        $LOG_to_BAK
        echo "done."
        ;;
    *)
        echo $"usage: $0 {start|sync|stop}"
        exit 1
        ;;

esac

exit 0
